; Theme 2DS Pokemon Crystal Red — 3DSoundShell
; Format: 0xRRGGBBFF

name=2DS Pokemon Crystal Red
bg_primary=0x4a000bff
bg_secondary=0x380005ff
bg_header=0x250002ff
bg_selected=0x7d0016ff
bg_playing=0x630010ff
text_primary=0xffffffff
text_secondary=0xffe6e9ff
text_accent=0xff8093ff
text_disabled=0xffb3beff
accent=0x7b3d45ff
accent2=0x91001aff
border=0x6e0013ff
scrollbar=0x54000cff
progress_bg=0x2e0004ff
progress_fill=0xff0033ff
eq_bar=0xffffffff
eq_handle=0xffe0e6ff
eq_bar_selected=0xffd700ff
eq_bar_positive=0x00cc44ff
eq_bar_negative=0xff2244ff
eq_zero_line=0x6e0013ff
eq_bg=0x1a0003ff
vis_start=0xff0033ff
vis_end=0xffffffff