; Theme New 2DS Blue Violet — 3DSoundShell
; Format: 0xRRGGBBFF

name=New 2DS Blue Violet
bg_primary=0x25114dff
bg_secondary=0x1a0b36ff
bg_header=0x110524ff
bg_selected=0x491f8aff
bg_playing=0x38146eff
text_primary=0xd6c2ffff //nom music + barre prog
text_secondary=0xa385e0ff //info pri
text_accent=0xbb00ffff //3DSoundShell
text_disabled=0x51387dff //info sec
accent=0x6c62bfff //PLAY, info sec et Dossier indic
accent2=0x612cb0ff
border=0x441b80ff
scrollbar=0x351266ff
progress_bg=0x160730ff
progress_fill=0x1500ceff
eq_bar=0xd6c2ffff
eq_handle=0xf3ebffff
eq_bar_selected=0xffd700ff
eq_bar_positive=0x00cc44ff
eq_bar_negative=0xff2244ff
eq_zero_line=0x441b80ff
eq_bg=0x0c021aff
vis_start=0x006effff
vis_end=0xff00ffff